package com.github.spud.tinystore.inventory.domain.exception;

/**
 * 错误码枚举
 */
public enum InventoryErrorCode {
	INV_STOCK_NOT_FOUND,
	INV_AVAILABLE_NOT_ENOUGH,
	INV_RESERVATION_NOT_FOUND,
	INV_RESERVATION_STATE_INVALID,
	INV_IDEMPOTENT_REPLAY,
	INV_ADJUST_ILLEGAL,
	INV_ARG_INVALID,
	INTERNAL_ERROR,
	// 新增
	INV_OUTBOX_PERSIST_FAIL,
	INV_STOCK_CONCURRENT_CONFLICT,
	INV_INVARIANT_BROKEN,
	INV_EVENT_DISPATCH_FAIL
}
