<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.github.spud.tinystore</groupId>
		<artifactId>tiny-store</artifactId>
		<version>1.0-SNAPSHOT</version>
	</parent>

	<artifactId>tinystore-domain-gateway</artifactId>
	<description>
		路由转发、协议转换（HTTP/HTTPS -> 内部 RPC）、鉴权（基于用户 Token 与权限体系）
	</description>

	<properties>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>
	
	<dependencies>
		<dependency>
			<groupId>com.github.spud.tinystore</groupId>
			<artifactId>tinystore-library-infrastructure</artifactId>
			<version>1.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-gateway-server-webflux</artifactId>
		</dependency>
	</dependencies>

</project>