server:
  port: 8000
spring:
  application:
    name: tinystore-domain-account
  datasource:
    url: jdbc:postgresql://localhost:5432/tinystore?currentSchema=tinystore_account
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    stream:
      bindings:
        userCreated-out-0:
          destination: user-created
          content-type: application/json
        userUpdated-out-0:
          destination: user-updated
          content-type: application/json
        userStatusChanged-out-0:
          destination: user-status-changed
          content-type: application/json
        userCredentialChanged-out-0:
          destination: user-credential-changed
          content-type: application/json
      rabbit:
        bindings:
          userCreated-out-0:
            producer:
              transacted: true
          userUpdated-out-0:
            producer:
              transacted: true
          userStatusChanged-out-0:
            producer:
              transacted: true
          userCredentialChanged-out-0:
            producer:
              transacted: true
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        access-key:
        import-check:
          enabled: false
      discovery:
        server-addr: 127.0.0.1:8848
        access-key:
# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

tinystore:
  internal:
    call-token: ${TINYSTORE_INTERNAL_CALL_TOKEN:changeit}

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/tinystore_test?currentSchema=tinystore_account

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://prod-db:5432/tinystore?currentSchema=tinystore_account
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
