apiVersion: v1
kind: Service
metadata:
  name: tinystore-gateway
  labels:
    app: tinystore-gateway
spec:
  selector:
    app: tinystore-gateway
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
